spring:
  application:
    name: ui-app
server:
  port: 8080

math:
 service:
  base:
   url: http://localhost:8081/math
  square:
   url: /square
  cube:
   url: /cube
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   
#   enabled: false

#-Deureka.client.enabled=false